--In case we want sequence strategy
--CREATE  sequence  group_seq;
--CREATE  sequence  group_seq_comment;

CREATE TABLE USER(
--USER_ID BIGINT PRIMARY KEY,
USER_NAME VARCHAR(255) PRIMARY KEY,
CREATED_ON TIMESTAMP
);

CREATE TABLE POST(
POST_ID BIGINT default group_seq.nextval PRIMARY KEY,
POST_DESCRIPTION VARCHAR(2000),
USER_NAME VARCHAR(255),
LATITUDE DOUBLE,
LONGITUDE DOUBLE,
TEMPERATURE DOUBLE,
CITY VARCHAR(255),
CREATED_ON TIMESTAMP,
FOREIGN KEY (USER_NAME) REFERENCES USER(USER_NAME)
);

CREATE TABLE POST_COMMENTS(
COMMENT_ID BIGINT PRIMARY KEY,
POST_ID BIGINT,
COMMENT VARCHAR(2000),
CREATED_ON TIMESTAMP,
FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID)
);




